### ISSUE TITLE
load-success event triggers when <img> still empty

### ISSUE THREAD

**Issue by marcemira** [huafu/ember-img-manager#1]
Hello, I was trying to use this event in order to set height of a absolute element equal to img height, but at that time all I have is the

``` html
<img>
```

tag. Is it possible to access to the native image object inside an action,  in order to get this property? Thanks!

**Comment by huafu** [comment]
What version are you using? I have been fixing a critical bug yesterday, lemme know what looks like your `{{img}}` code and the associated controller/view handle the `load-success`.

**Comment by marcemira** [comment]
Using ember-img-manager 0.0.7. The handlebars:

``` hbs
{{img-wrap src=event.image load-success="fadeIn"}}
```

actions inside the component:

``` javascript
...
actions: {

    fadeIn: function () {

      var _this = this.element,
          event_actions = _this.parentNode.querySelector('.event-actions'),
          description = _this.parentNode.querySelector('.content-description'),
          img = _this.querySelector('.content-viewer img');

      // I need to set content-description height = content-viewer height
      // content-viewer height is given naturally by img height + margin.
      // after img has loaded and gave it the height, I should set the content-viewer height.
      // but at this moment, img its just an empty tag, no src, hence, can't get height :(

      Ember.$.Velocity(img, {'opacity':1}, 250);
      Ember.$.Velocity(event_actions, {'opacity':1}, 250);
      description.style.height = getComputedStyle(_this.parentNode.querySelector(".content-viewer")).height; // this won't work :(

    }

  }
...
```

Thanks in advance :+1:

**Comment by huafu** [comment]
Well first of all, you should be using `this.$` and all jQuery functions if you're going to do some jQuery at the end. Then you might be able to solve your issue with pure css, floats, and the famous `clear-fix` _hack_.

Anyway, that is not solving the issue. It sounds like there is an issue about the event. Is the image showing something at the moment it goes in `fadeIn`. Like if you put a breakpoint out there?

**Comment by marcemira** [comment]
@huafu Thanks for responding. I'm avoiding as much jQuery as possible in that part in order to boost performance a little, but this is a context not related to the issue. I did put a breakpoint in the middle to see what's going on there and in fact the img at the dom is an empty img tag, no src, hence not even rendered at the break point time. Is there a way to access the img instance from the event? something like an action parameter would be great... Thanks!

**Comment by huafu** [comment]
I guess I am triggering the `success` event too early then, will check that now

**Comment by marcemira** [comment]
Is it possible to have something like this?

``` javascript
...
actions: {

    fadeIn: function (img) { // <---- action parameter

        var imgHeight = img.height;
...
```

**Comment by huafu** [comment]
Yes, will add that too. I confirm it's a bug anyway, just looking at the code. I meant, the source img is loaded, but the clone is not yet replaced into the DOM

**Comment by marcemira** [comment]
I just noticed that looking at the code :+1:

**Comment by huafu** [comment]
Ok I've not only fixed that, also refactored the way clones were handled, now it's much better. Version `0.0.8`, just realized that I didn't test the events (no time :-/) so reopen this issue in case the bug is still here.

Btw what I did also fixed a bug where sometimes the images won't even display at all.

You should have the node as first parameter of the action handler.
