### ISSUE TITLE
[BUG] App crashes after 0.0.8

### ISSUE THREAD

**Issue by marcemira** [huafu/ember-img-manager#2]
Hello again, after installing 0.0.8, the app breaks throwing this:

```
Assertion Failed: [img-manager] Can't get a clone with no `src`.
```

Every `{{img-wrap}}` has a src. 

Debuging a bit, the problem seems to be that you are trying to clone an img before the node its even ready, img is still `<img>` and isSuccess it's still `false`, hence it will fail an assert that ask for src attrb... Any thoughts? Thanks man!

**Comment by huafu** [comment]
Weirdo! I definitely have o find some time to write unit tests. Dropping an eye on that now.

**Comment by huafu** [comment]
Hoho! so I got to add some acceptance tests, and of course fixed that bug, plus another one which would not set attributes! `v0.0.9` released, check-it out! And thanks for reporting!

**Comment by marcemira** [comment]
:+1:  Works flawless! thanks!
