### ISSUE TITLE
[FEATURE] Add `render-success` and `render-error` hooks called once loaded (or fail) and rendered

### ISSUE THREAD

**Issue by marcemira** [huafu/ember-img-manager#3]
You must hate me by now, I'm sorry :p. But here's a last small request for this fantastic addon. I thought it would be awesome to have a hook that triggers an action after the img did render, since the load-success event is called only after the img is loaded from server, it won't work when the image is cached on a second visit... So, it would be a way to call an action after image is rendered, in any case. Hope you get the general idea. Thanks in advance!

**Comment by huafu** [comment]
No i not hate you, it's the opposite. To make great addons with great features, it needs the most input possible ;-)
Tho I might work on this only in a week or too :-s

**Comment by huafu** [comment]
@marcemira actually the `load-success` and `load-error` are/should be triggered per `{{img-wrap}}` no matter if they are the same or not. Are you sure you didn't go to another route and then came back to the route where you had those events, in which case no render is done and the views are just re-used?

**Comment by marcemira** [comment]
@huafu Hey, thanks for answering man, the -you must hate me- thing was a joke :P. In my case, the img always get render, but what I was pointing out is to create a hook at the time the img gets render, in order to work with (ie.) the size properties. This will work both when the img has just load from server and when it is cached (cloned). Right now i'm using load-success because is the only way there is to trigger something after render, but as I said before, it won't work when go and back from app routes. Thanks again for the awesome work!

**Comment by huafu** [comment]
Well if it wasn't a joke you wouldn't write this :p.
Anyway, there is a bug in it in fact, yes another one. I wrote an acceptance test yesterday, fixed the load-success so that it is called as expected (ie for each `img-wrap` as soon as it is rendered), but still get to fix the load-error one which actually never get called for some reason.

**Comment by huafu** [comment]
`0.0.10` is fixing this. `load-success` and `load-error` are now triggered for each `{{img-wrap}}`

**Comment by marcemira** [comment]
Hey! I just updated to 0.0.10 and everything is working as expected! many thanks! :D :+1:

**Comment by huafu** [comment]
SOrry that it is coming with lag, I have so much work on many other projects. If you happen to see any other issue please report. If you happen to have some time, please write a PR with some more tests lol

**Comment by marcemira** [comment]
No problem, I understand since have a bunch of projects I work on every day too :+1: . Btw, I just noticed that if an image fails to loading, it will be replaced randomly by one of the ones that did success :p, which produces very funny effects lol. I'll give you a rest and take a look at that later by myself, and if I got it fixed i'll send a PR.

**Comment by huafu** [comment]
?? wtf lol! Well this is something that has to be fixed asap lol. If you do not look soon please create an issue so that I do not forget! And if you do fix it please begin by writing a failing acceptance test and then fix the code to fix it. I should have been doing that since the beginming, time is badly the issue ;-)
