### ISSUE TITLE
[Deprecation Warnings] Update to 1.11.0

### ISSUE THREAD

**Issue by marcemira** [huafu/ember-img-manager#9]
There is a deprecation warning when using binded styles:

http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes

**Comment by artsmc** [comment]
just when I thought I found a solution

**Comment by huafu** [comment]
Forgive me if I read you wrong, I'm not fluent in English, but @artsmc is this sarcastic? Because PRs are welcome, I do those  open-source addons in my free time, and as you can see I have NO free time lately.

**Comment by artsmc** [comment]
:+1: i see what you did there. I normally just fix it myself when i can't find a solution (rare cases). If I have time i'll contribute a solution to the project. But i know what you mean about free time lol

**Comment by artsmc** [comment]
According to the depreciation documentation for this error:
http://emberjs.com/deprecations/v1.x/#toc_warning-when-binding-style-attributes
html as well as css has to be turned into a safe string. So in the component i made the change.

``` javascript
/**
  * The css styles of our span
 * @property style
  * @type {string}
 */
 //style: 'display: inline-block;',
 style: function() {
 return ("display:inline-block").htmlSafe();
 }.property('style'),
```

And that fixes the warning messages. 

:wink: hope the sarcasm didn't come off the wrong way

**Comment by marcemira** [comment]
It may be safer to use Ember.computed(function(){ ... }) instead of .property('style')
